theme: minima
title: Some thoughts about life, society, economics and science.
description: This site is meant to be anonymous for the time being.
repository: rainyalgorithm/rainyalgorithm.github.io

# Build settings
markdown: kramdown
permalink: pretty
paginate: 3
