theme: jekyll-theme-slate
title: Some thoughts about life, society and science.
description: This site is meant to be anonymous for the time being.
repository: rainyalgorithm/rainyalgorithm.github.io
